/******************************************************************************
*
*       SYSNAME.H - Windows 2002 Driver Name Definition
*
*               Copyright (c) 2002 AIdesign
*
*       PURPOSE: Define the driver name.
*
******************************************************************************/
#ifndef _SYSNAME_H_
#define _SYSNAME_H_

#define NAME_BASE           "ACCESS"
#define NAME_BASE_L         L"ACCESS"

#endif
